config/routes.rb
Rails.application.routes.draw do
  devise_for :users    #do get '/users/sign_out' => 'devise/sessions#destroy'
  resources :users
  resources :first_names
  resources :products

  resources :products do
    resources :comments
  end
  resources :users


  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'



  post 'payments/create'

  root 'static_pages#landing_page'    # root 'static_pages#landing_page'

  mount ActionCable.server => '/cable' #ActionCable runs on the same process as the app

  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/product.rb
class Product < ApplicationRecord #Start of class
  validates :name, presence: true #validation, checks whether name has been entered

  has_many :comments

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end

  def average_rating
    comments.average(:rating).to_f
  end

  def self.search(search_term)
    if Rails.env.production?
      Product.where("name ilike ?", "%#{search_term}%")
    else
      Product.where("name LIKE ?", "%#{search_term}%")
    end
  end

end # End of class

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index

    if params[:q]
      @products = Product.search(params[:q])
    else
      @products = Product.all
    end
      @products = @products.paginate(page: params[:page], per_page: 6)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC")
    @comments = @product.comments.paginate(page: params[:page], per_page: 4)
  end

  # GET /products/new
  def new
    #byebug
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json

# I have redirected users not to @product but to another page
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save #was before redirect_to @product
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end


  end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>



<!--<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>

            <% if signed_in? && current_user.admin? %>
              <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>

            </p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>

</div>-->

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li> <!--message-->
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <label><%= form.label :name %></label>
    <%= form.text_field :name, id: :product_name, :class => "form-control" %>
  </div>




  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-success" %>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body, class: "form-control col-lg input-lg" %>
    </p>

    <p>
      <div class="rating">

      </div>
    </p>

    <p>
      <%= f.submit "Submit", class: "btn btn-default btn-sm" %>
    </p>

  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-2 col-md-4">
  <% cache product do %><!-- Start of Cache -->
    <%=link_to image_tag(product.image_url, class: "image img-responsive"), product %>

    <h1><%= link_to product.name, product, class: "fade-in" %></h1>
    <p><%= product.description %></p>
      <% logger.debug "Product: #{product.name}" %>  <!-- Inserted logger debug -->
      <% logger.debug "Product: #{product.id}" %>  <!-- Inserted logger debug -->
    <strong>$ <%= product.price %></strong>
  <% end %><!-- /End of Cache -->
</div><!-- /col -->

app/views/products/edit.html.erb
<h3>Editing Product</h3>
<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
  <% if signed_in? && current_user.admin? %>
  <%= link_to 'New Product', new_product_path, class: 'pull-right btn btn-primary' %>
<% end %>

<!-- This is the Products Page -->

<div class="container">
  <h1>Products</h1>
  <% cache(cache_key_for_products) do %> <!-- Start of Cache -->
    <%= render @products, class: 'img-responsive' %>
  <% end %><!-- /End of Cache -->
</div>

  <%= will_paginate @products %><br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>
<div class="link-underline">
  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="row" data-product-id="<%= @product.id %>">
    <div class="col-xs-12 col-md-12">

      <p>
        <strong>Name:
        <%= @product.name %></strong>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <%=image_tag(@product.image_url, data_zoom_image: @product.image_url, class: " img_zoom img-responsive") %>
        <script>
          $('.img_zoom').elevateZoom();
        </script>
      </p>

      <p>
        <strong>Colour:</strong>
        <%= @product.colour %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= number_to_currency(@product.price) %>
      </p>



      <p>
        <strong>Highest Rating:</strong>
        <%= @product.highest_rating_comment.try(:rating) %>
      </p>
      <p>
        <strong>Lowest Rating:</strong>
        <%= @product.lowest_rating_comment.try(:rating) %>
      </p>

      <p>Average Rating:
        <div class="rated" id="average_rating" data-score="<%= @product.average_rating %>">
        </div>
      </p>

    </p>

    <%= form_tag "/payments/create" do %>
  <%= render partial: "shared/stripe_checkout_button" %>
  <%= hidden_field_tag(:product_id, @product.id) %>
<% end %>
    <p>

      <%= render 'new_comment' %>
      <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
      <%= render 'comments' %>

      <%= will_paginate @comments %><br>

        <% if signed_in? &&current_user.admin?  %>
          <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-default btn-sm" %> |
          <%= link_to 'Back', products_path, class: "btn btn-default btn-sm" %>
        <% end %>
    </div>
 </div>
</div>