config/routes.rb
Rails.application.routes.draw do
  devise_for :users    #do get '/users/sign_out' => 'devise/sessions#destroy'
  resources :users
  resources :first_names
  resources :products

  resources :products do
    resources :comments
  end
  resources :users


  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'



  post 'payments/create'

  root 'static_pages#landing_page'    # root 'static_pages#landing_page'

  mount ActionCable.server => '/cable' #ActionCable runs on the same process as the app

  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alens Biker Shop</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"><!-- Navbar starts here -->
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">
              <a href="#" class="navigation-header">Alens Biker Shop</a>
            </div>
          </div>

            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right navigation-header">
                <div class="search-form"><!-- Start of Search Form -->
                  <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
                  <%= form.text_field :q, id: 'q', value: params[:q], class: "color:black" %>
                  <%= form.submit 'Search', class: "search-button" %>
                  <% end %>
                </div><!-- /End of Search Form -->
                <li><%= link_to "HOME", root_path %></li>
                <li><%= link_to "PRODUCTS", products_path %></li>
                <li><%= link_to "ABOUT", static_pages_about_path %></li>
                <li><%= link_to "CONTACT", static_pages_contact_path %></li>
                <li><!-- Login -->
                  <% if user_signed_in? %>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                  <% else %>
                  <%= link_to "Login", new_user_session_path %>
                  <% end %>

                </li><!-- /End of Login -->
              </ul>
            </div>
          </div>
        </nav><!-- /End of Navbar -->

  <%= yield %>

    <div class="footer navbar-fixed-bottom">
      &copy; 2017 Bikers Shop <%= Time.now %>
    </div><!-- /End of Footers -->

      <% if notice %><!-- Notice and Alert -->
          <p id="notice" class="alert alert-info"><%= notice %></p> <!-- alert is a bootstrap component -->
      <% end %>
      <% if alert %>
        <p id="alert" class="alert alert-warning"><%= alert %></p>
      <% end %><!-- /End of Notice and Alert -->

    <!-- Login Fadeout-->
    <script>
    $(".alert").fadeOut(4000);
    </script><!-- End of Login Fadeout -->

  </body>
  </html>